from PyQt6.QtWidgets import QWidget, QVBoxLayout, QHBoxLayout, QLabel, QLineEdit, QPushButton, QComboBox, QStackedWidget, QFileDialog, QDateEdit

class StudentRegisterWindow(QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Register Student")
        self.stack = QStackedWidget()
        self.init_step1()
        self.init_step2()
        self.init_step3()
        layout = QVBoxLayout()
        layout.addWidget(self.stack)
        self.setLayout(layout)

    # Step 1: Student Information
    def init_step1(self):
        step1 = QWidget()
        layout = QVBoxLayout()
        self.name_input = QLineEdit()
        self.gender_input = QComboBox()
        self.gender_input.addItems(["Male", "Female"])
        self.dob_input = QDateEdit()
        self.email_input = QLineEdit()
        self.phone_input = QLineEdit()
        self.pob_input = QLineEdit()
        next_btn = QPushButton("Next")
        next_btn.clicked.connect(lambda: self.stack.setCurrentIndex(1))

        layout.addWidget(QLabel("Name"))
        layout.addWidget(self.name_input)
        layout.addWidget(QLabel("Gender"))
        layout.addWidget(self.gender_input)
        layout.addWidget(QLabel("DOB"))
        layout.addWidget(self.dob_input)
        layout.addWidget(QLabel("Email"))
        layout.addWidget(self.email_input)
        layout.addWidget(QLabel("Phone"))
        layout.addWidget(self.phone_input)
        layout.addWidget(QLabel("Place of Birth"))
        layout.addWidget(self.pob_input)
        layout.addWidget(next_btn)
        step1.setLayout(layout)
        self.stack.addWidget(step1)

    # Step 2: Course Info
    def init_step2(self):
        step2 = QWidget()
        layout = QVBoxLayout()
        self.from_school_input = QLineEdit()
        self.grade_input = QLineEdit()
        self.major_input = QLineEdit()
        self.study_shift_input = QComboBox()
        self.study_shift_input.addItems(["Morning", "Afternoon", "Evening"])
        next_btn = QPushButton("Next")
        next_btn.clicked.connect(lambda: self.stack.setCurrentIndex(2))
        back_btn = QPushButton("Back")
        back_btn.clicked.connect(lambda: self.stack.setCurrentIndex(0))

        layout.addWidget(QLabel("From School"))
        layout.addWidget(self.from_school_input)
        layout.addWidget(QLabel("Grade"))
        layout.addWidget(self.grade_input)
        layout.addWidget(QLabel("Major"))
        layout.addWidget(self.major_input)
        layout.addWidget(QLabel("Study Shift"))
        layout.addWidget(self.study_shift_input)
        layout.addWidget(next_btn)
        layout.addWidget(back_btn)
        step2.setLayout(layout)
        self.stack.addWidget(step2)

    # Step 3: Parents Info
    def init_step3(self):
        step3 = QWidget()
        layout = QVBoxLayout()
        self.father_name_input = QLineEdit()
        self.father_job_input = QLineEdit()
        self.father_phone_input = QLineEdit()
        self.mother_name_input = QLineEdit()
        self.mother_job_input = QLineEdit()
        self.mother_phone_input = QLineEdit()
        self.relative_input = QLineEdit()
        self.relative_job_input = QLineEdit()
        self.relative_phone_input = QLineEdit()
        submit_btn = QPushButton("Submit")
        submit_btn.clicked.connect(self.submit)
        back_btn = QPushButton("Back")
        back_btn.clicked.connect(lambda: self.stack.setCurrentIndex(1))

        layout.addWidget(QLabel("Father Name"))
        layout.addWidget(self.father_name_input)
        layout.addWidget(QLabel("Father Job"))
        layout.addWidget(self.father_job_input)
        layout.addWidget(QLabel("Father Phone"))
        layout.addWidget(self.father_phone_input)
        layout.addWidget(QLabel("Mother Name"))
        layout.addWidget(self.mother_name_input)
        layout.addWidget(QLabel("Mother Job"))
        layout.addWidget(self.mother_job_input)
        layout.addWidget(QLabel("Mother Phone"))
        layout.addWidget(self.mother_phone_input)
        layout.addWidget(QLabel("Relative"))
        layout.addWidget(self.relative_input)
        layout.addWidget(QLabel("Relative Job"))
        layout.addWidget(self.relative_job_input)
        layout.addWidget(QLabel("Relative Phone"))
        layout.addWidget(self.relative_phone_input)
        layout.addWidget(submit_btn)
        layout.addWidget(back_btn)
        step3.setLayout(layout)
        self.stack.addWidget(step3)

    def submit(self):
        # Here you save data to DB
        # You can collect all .text() values and save them using your models
        print("Registration complete!")
        self.close()
